module.exports = {
  VIEW_DEVICES: "COMMAND_VIEW_DEVICES",
  SETTINGS: "COMMAND_SETTINGS",
  BACK_TO_START: "COMMAND_BACK_TO_START",
  // on register device button click
  REGISTER_DEVICE: "REGISTER_DEVICE",
  // on edit device button click
  EDIT_DEVICE: "EDIT_DEVICE",
  EDIT_DEVICE_ID: "EDIT_DEVICE_ID",
  EDIT_DEVICE_NAME: "NAME",
  EDIT_DEVICE_PRODUCT_NAME: "PRODUCT_NAME",
  EDIT_DEVICE_MAX_WEIGHT: "MAX_WEIGHT",
  // on delete device button click
  DELETE_DEVICE: "DELETE_DEVICE",
  DELETE_DEVICE_ID: "DELETE_DEVICE_ID"
};
